import React, { Component, Fragment } from 'react'
import Home from '../../layouts/Home'
import {Grid } from '@material-ui/core/'
import CardContent from '@material-ui/core/CardContent';
import Typography from '@material-ui/core/Typography';
import { withStyles } from '@material-ui/core/styles';
import Card from '@material-ui/core/Card';

const styles = theme => ({
    root: {
      flexGrow: 1,
      marginTop: 'auto',
    },
    card: {
        marginTop:'10%',
        marginBottom:'5%',
        maxWidth: '100%',
    },
    
});

class PrivacyPolicy extends Component {
    render() {
        const { classes} = this.props
        return (
            <Home>
                <Fragment className={classes.root}>
                <Grid item>
                    <Card className={classes.card}>
                    <CardContent>
                        <Typography variant="title" gutterBottom > Privacy Policy </Typography>
                        <Typography variant="overline" align="right" gutterBottom> Effective date: January 20, 2019 </Typography>
                        <Typography component="p" variant="body1" align="left"> 
                        CHI operates the “https://app-chi.firebaseapp.com/upin” website and 
                        the CHI mobile application (referred to as the "Service").
                        This page informs you of our policies regarding the collection, use, 
                        and disclosure of personal data when you use our Service and the choices 
                        you have associated with that data. The Privacy Policy for CHI is based 
                        on the TermsFeed's Privacy Policy Template.
                        We use your data to provide and improve the Service. 
                        By using the Service, you agree to the collection and use of information 
                        in accordance with this policy. Unless otherwise defined in this Privacy Policy, 
                        the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.
                        </Typography>
                        </CardContent>

                        <CardContent>
                        <Typography variant="subtitle1" align="left"gutterBottom> Definitions </Typography>
                        <Typography component="p" variant="body1" align="left">
                        <Typography variant="subtitle2" align="left"gutterBottom> 1. Service </Typography>
                        Service means the https://app-chi.firebaseapp.com/upin website and 
                        the CHI mobile application operated by CHI
                        <Typography variant="subtitle2" align="left"gutterBottom> 2. Personal Data </Typography>
                        Personal Data means data about a living individual who can be identified
                        from those data (or from those and other information either in our 
                        possession or likely to come into our possession).
                        <Typography variant="subtitle2" align="left"gutterBottom> 3. Usage Data </Typography>
                        Usage Data is data collected automatically either generated by 
                        the use of the Service or from the Service infrastructure itself 
                        (for example, the duration of a page visit).
                        <Typography variant="subtitle2" align="left"gutterBottom> 4. Cookies </Typography>
                        Cookies are small files stored on your device (computer or mobile device).
                        </Typography>
                        <Typography variant="body1" align="right" gutterBottom> Publishing Content. </Typography>
                        </CardContent>

                        <CardContent>
                        <Typography variant="subtitle1" align="left"gutterBottom> Information Collection and Use </Typography>
                        <Typography component="p" variant="body1" align="left">
                        We collect several different types of information for various purposes to provide and improve our Service to you.
                        Our Service does use third party services that may collect information used to identify you.
                        Please see the privacy policy of these third-party service providers which used by our Service.
                        <Typography component="p" variant="body1" align="left">
                        -	Facebook
                        </Typography>
                        <Typography component="p" variant="body1" align="left">
                        -	Firebase Analytics
                        </Typography>
                        </Typography>
                        </CardContent>

                        <CardContent>
                        <Typography variant="subtitle1" align="left"gutterBottom> Types of Data Collected </Typography>
                        <Typography variant="subtitle2" align="left"gutterBottom> 1. Personal Data </Typography>
                        <Typography component="p" variant="body1" align="left">
                        While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:
                        <Typography component="p" variant="body1" align="left">
                        •	Email address
                        </Typography>
                        <Typography component="p" variant="body1" align="left">
                        •	First name and last name
                        </Typography>
                        <Typography component="p" variant="body1" align="left">
                        •	Profile images
                        </Typography>
                        <Typography component="p" variant="body1" align="left" gutterBottom>
                        •	Cookies and Usage Data
                        </Typography>
                        </Typography>
                        <Typography variant="subtitle2" align="left"gutterBottom> 2. Usage Data </Typography>
                        <Typography component="p" variant="body1" align="left" gutterBottom>
                        We may also collect information that your browser sends whenever you visit our Service or when you access the Service by or through a mobile device ("Usage Data").
                        This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                        When you access the Service by or through a mobile device, this Usage Data may include information such as the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data.
                        </Typography>
                        <Typography variant="subtitle2" align="left"gutterBottom> 3. Tracking Cookies Data </Typography>
                        <Typography component="p" variant="body1" align="left" gutterBottom>
                        We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.
                        Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyse our Service.
                        You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.
                        </Typography>
                        </CardContent>
                        
                    </Card>
            </Grid>
            </Fragment>
            </Home>
        )
    }
}
export default withStyles(styles)(PrivacyPolicy)